### ISSUE TITLE
Communication and Ambassadors (Karam Yahya, Ruthy da Vinca, Ali Ghali, Veronika Ban, Klara - Leona Lorca, Rike Flaemig)

### ISSUE THREAD

**Issue by ninabreznik** [RefugeesWork/roadmap#1]
### Connect with partners:
* UN Women (Ruthy)
* ??

**Comment by ninabreznik** [comment]
>What we need is the word to go out about the initiative www.refugeeswork.com.  Ambassadors who could help refugees make their profiles. For now we are focusing on getting in jobs/gigs that are not paid, at least not with money, more with some form of exchange (clothes, food, connections, help back...). People who post "jobs" are the ones who want to connect to refugee community and to help them one by one. This is the way to get new friends in your new local community and then things will start to open...

**Comment by serapath** [comment]
i answered on disqus :-)

**Comment by LizeeAK** [comment]
check out this article , unfortunately it is only in german:

http://www.dw.com/de/das-ist-totales-staatsversagen/a-18762500

but it quotes an Enayatuila Sediqi, guy from Afghanistan, who offers his help as translator. 

plus it would be a good idea to go to  LaGeSo, as you can read you have many people queing there everyday, so many people you can promote the app with. maybe you do Flyers or sth like that , which could be distributed there?

**Comment by LizeeAK** [comment]
what happened to the list german classes/ refugee Centers? can we post it here?

**Comment by ninabreznik** [comment]
Issue is moved here https://github.com/RefugeesWork/roadmap/issues/17
