### ISSUE TITLE
How to promote the app among potential employers (new job posts) ?

### ISSUE THREAD

**Issue by LizeeAK** [RefugeesWork/roadmap#12]
### How-to?
* ambassadors (Bianca?)
* social media (Nina, Alice)
* PR - see Issue [ https://github.com/RefugeesWork/roadmap/issues/11 ]

**Comment by LizeeAK** [comment]
ideas:

-press release (make a list with all Kind of german media)
- social media marketing
-??

**Comment by ninabreznik** [comment]
:+1: 

What do you think - could "your" journalists work on this? Should we put one of the points of their focus to be building awareness amongst employers?
