### ISSUE TITLE
Mobile App (Daniel, Alex, Nina and Wilson)

### ISSUE THREAD

**Issue by ninabreznik** [RefugeesWork/roadmap#13]
### Mobile app

* MVP (minimal viable product -  just to basic things - refugees can check and apply to new jobs (notifications), employers can post jobs --> so no edit profile etc. things)
* Mockup
* APIs
* Cordova? Native app?

**Comment by ninabreznik** [comment]
@serapath, @wilsonpinto, @dahie - how do we get started?

**Comment by wilsonpinto360** [comment]
Hello,

i am currently working as mobile developer using cordova + ionic framework to build hybrid applications, i think that is the best choice for this kind of app.

I can also build server api using php

**Comment by wilsonpinto360** [comment]
Simple mockup for start was nice, i am not designer so... :p

**Comment by serapath** [comment]
sounds great :-)
I'd say a server api might not be necessary, because the backend would probably be existing platforms, like for example the ruby on rails backend of refugeeswork.com, but probably soon other apps too :-)
