### ISSUE TITLE
Info Point (Veronika, Ruthy)

### ISSUE THREAD

**Issue by ninabreznik** [RefugeesWork/roadmap#14]
What is out there? 
* organisations
* apps
* infos
* etc.

**Comment by veronikaban** [comment]
Kiron University - Free education for refugees 
https://kiron.university/

**Comment by veronikaban** [comment]
The German Asylum Procedure Infos:
http://www.lichtenberg-hilft.de/index.php?id=266

**Comment by veronikaban** [comment]
Refugee Phrasebook/Phrases for Helpers:
http://www.refugeephrasebook.de/pdf/helpersDE150928.pdf

**Comment by veronikaban** [comment]
FACEBOOK PAGES / GROUPS :

Refugees Welcome:
https://www.facebook.com/RefugeesWellcome?ref=ts&fref=ts

Refugees.Work.com:
https://www.facebook.com/groups/RefugeesWork/

Refugees Welcome to Slovenia:
https://www.facebook.com/refugees.slovenia?fref=ts

Gesichtzeigen! Für ein weltoffenes Deutschland:
https://www.facebook.com/gesichtzeigen

Hire a refugee:
https://www.facebook.com/HIRE-A-Refugee-1650499918501543/timeline/

Maribor pomaga beguncem / Slovenia helps Refugees:
https://www.facebook.com/Maribor-pomaga-beguncem-do-avstrijske-meje-569359309869346/timeline/

Are you syrious / Slovenia helps Refugees:
https://www.facebook.com/Are-you-syrious-Maribor-pomaga-beguncem-814496498648343/timeline/

Refugees Welcome to Croatia:
https://www.facebook.com/dobrodosli.dragi.imigranti?fref=ts

Refugees Welcome International:
https://www.facebook.com/refugeeswelcomeinternational?fref=ts

**Comment by veronikaban** [comment]
ORGANISATIONS / PLACES : 

Refugees Welcome:
http://www.refugees-welcome.net/

Fremde Freunde Berlin:
http://www.fremdefreunde.berlin/

Give Something Back To Berlin:
http://givesomethingbacktoberlin.com/

**Comment by ninabreznik** [comment]
:+1:  Awesome job, @veronikaban

**Comment by veronikaban** [comment]
WHERE / HOW TO HELP IN BERLIN:

Berlin Hilft:
https://netzwerkfluechtlingeberlin.wordpress.com/2015/08/21/overview-about-this-website/

Place to sleep in Berlin:
http://place4refugees.de/
