### ISSUE TITLE
Messaging app for team

### ISSUE THREAD

**Issue by wilsonpinto360** [RefugeesWork/roadmap#16]
Do you already have some chat where we can share some ideas?

if not i would recommend that we create RefugeesWork team on [Slack](https://slack.com/), it's very cool and best of all its completly free.

I use it everyday to communicate with my php community.

**Comment by ninabreznik** [comment]
We use Gitter. Maybe that would be best, because it's connected to Github repo. I will open it and share it with you.

**Comment by wilsonpinto360** [comment]
ok perfect :)
