### ISSUE TITLE
Blog content

### ISSUE THREAD

**Issue by ninabreznik** [RefugeesWork/roadmap#19]
- contributors (Karam, Salman, Alice)
- content (related to work/jobs)

**Comment by LizeeAK** [comment]
Do we have a name for the blog already?

**Comment by ninabreznik** [comment]
We were talking last time to make it as a button from RefugeesWork so no special name, it's going to be on RefugeesWork/blog. But maybe it could have a welcome message and short intro to explain what it is all about.
