### ISSUE TITLE
Create Donate button

### ISSUE THREAD

**Issue by ninabreznik** [RefugeesWork/roadmap#27]
Cover hosting and other costs with donations

**Comment by dgmora** [comment]
I was investigating a bit on doing a donate button with paypal. I made it work in the paypal testing server with my e-mail, it's not very difficult. 
What we could need:
- Create testing account(s) in paypal sandbox, linked to an e-mail from refugeeswork that would receive testing payments (and issue them. With those accounts we can test locally, and in automated tests if needed). Log to your paypal account [here](https://developer.paypal.com/developer/accounts/), from there you will be able to create test accounts for the sandbox server.
- Create/use a real paypal account for production. I don't have refugeeswork e-mail access, so someone should set this up. 
- Set the donate button in the paypal account (test and prod). [Here](https://developer.paypal.com/docs/classic/paypal-payments-standard/integration-guide/donate_step_1/) are the instructions
- Paste the code provided by paypal somewhere, and use the the server url and merchant id based on the environment.

**Comment by ninabreznik** [comment]
Ole! Did you maybe check how much Paypal takes for its service?

**Comment by serapath** [comment]
Yeah, that would be interesting to compare.
Paypal is the most popular, but might not be the cheapest :-)
I have a few more bookmarked
* https://gratipay.com/
* https://www.donorhut.com/pricing
* http://donate.ly/pricing/

But I guess that it also depends what is available where potential donors live.
I guess paypal is not too bad? ...just it costs again once you want to withdraw money from paypal...

**Comment by dgmora** [comment]
Paypal is 2.2% + 0.30 cent per transaction if you're non profit, or 2.9%+ 30 cent. Which means for 5€ they take 0.41/0.445 cents, 0.52/0.59 cents from 10€ . Gratipay seems similar to paypal, and donate.ly is a bit cheaper, if the amounts are smaller (3/4 %). 

The 'bad' thing is that paypal is trusted, and some people might only donate through paypal...I'd implement both and write something that asks the user to donate through donate.ly if possible.

@serapath I don't have e-mail/paypal access to refugeeswork, I'd need that to go on

**Comment by ninabreznik** [comment]
I agree, people trust Paypal more I guess, specially our potential supporters that come from probably more traditional background... Are you coming to the hackathon on saturday, @dgmora? Because we could implement this there...

**Comment by dgmora** [comment]
Sadly I have visit and I can't...

**Comment by ninabreznik** [comment]
Ooo, too bad. Then the next time :) Will keep you posted about stuff we will build on the hackathon...
