### ISSUE TITLE
App improvements (Nina Breznik)

### ISSUE THREAD

**Issue by ninabreznik** [RefugeesWork/roadmap#3]
From all the issues +

To be done:

* [ ] sorting jobs (by the city?) (Nina)

**Comment by LizeeAK** [comment]
translation to arabic: what happened with my friend rashid? do you want me to ask him again?
sorting jobs/city: yes, i think this will be definetly usefull once there are more jobs

We can do it! :)

**Comment by Dahie** [comment]
Given the city, we could do some basic geolocation, get current location from the browser and search for nearby jobs.

**Comment by serapath** [comment]
Maybe it's too early, but there is an organization that I think is pretty inspirational and we might be able to copy some concepts from them: https://www.freelancersunion.org/

If not for refugeeswork.com then maybe for codingamigos.com, but anyways, in the long run both apps might overlap in scope anyway.

**Comment by ninabreznik** [comment]
Add BLOG section
