### ISSUE TITLE
Refugee Data Analysis

### ISSUE THREAD

**Issue by ninabreznik** [RefugeesWork/roadmap#39]
- number of refugees
- demography
- self employment
- RefugeesWork users data

**Comment by cyberbikepunk** [comment]
At this point it's not so much data analysis, but rather detective work to find out if there are any sources of data.

**Comment by cyberbikepunk** [comment]
I'll come on the 25th and do some research

**Comment by cyberbikepunk** [comment]
Can you give me the rights to assign myself to the issue and create labels etc..?

**Comment by ninabreznik** [comment]
Great. I'll add you! Thanks (:

**Comment by ninabreznik** [comment]
We can also analyse data from the app (how many users, how often they come back, how many times they responded to the offers, where are they located, where are they originally from...)

**Comment by cyberbikepunk** [comment]
There is a section on the level of education of refugees., The only one i found so far. http://www.faz.net/aktuell/wirtschaft/wirtschaftspolitik/deutschlands-fluechtlinge-in-grafiken-13867210.html
