### ISSUE TITLE
Legal issues around payment (Alexander Praetorius and Faircoin?)

### ISSUE THREAD

**Issue by ninabreznik** [RefugeesWork/roadmap#4]
How can new arrivals without "Arbeitserlaubnis" (work allowance) get paid for work?

* minimum tax free earnings (Is there something like that (i.e. Fiverr)? If yes, do you need to register somewhere? )

* Bitcoin or other crypto-currencies (natural exchange)

* co-ownership of a company (no salary but payments in dividends)

* single person company

**Comment by LizeeAK** [comment]
http://www.dw.com/en/top-stories/germany-guide-for-refugees/s-32486

they have it arabic, in dari in pashtu as well
