### ISSUE TITLE
Introduction video (Alice Kohn, Ali Ghali + maybe Luka Tisler)

### ISSUE THREAD

**Issue by ninabreznik** [RefugeesWork/roadmap#8]
## How it works
* video in english and arabic
* Luka Tisler said he could help with graphics/text/animation, but only at the end of October

**Comment by LizeeAK** [comment]
hey just giving some updates here:

-send the sound of the video to a friend of a friend, she is a professional. she is in London next week, but will do it after she comes back
-sent ali the arabic version so he can tell me the times for me to cut
-any news on the animation?

that s all tha is missing :)

**Comment by ninabreznik** [comment]
:+1: 

My friend is currently in Cambodia, but will be back end of october and said he can do the animations! Ole :)

**Comment by LizeeAK** [comment]
Luka is working on the animation. rest is done!!
