### ISSUE TITLE
APIs (Daniel (@dahie), Alexander Praetorius and Wilson)

### ISSUE THREAD

**Issue by ninabreznik** [RefugeesWork/roadmap#9]
### APIs to be able to connect more apps/other projects

* Make a list of apps for refugees and sketch ideas how to connect them with us

**Comment by serapath** [comment]
+1 i can help brainstorm. @dahie what's your thoughts on it?

**Comment by ninabreznik** [comment]
Thanks, @serapath :+1:

**Comment by Dahie** [comment]
The original idea of an API came, because I was looking for a small mobile-app project using one of the JS-mobile frameworks (ionic, angular-mobile, haven't decided) for try-out. However that would just be for prototyping. An actual native app could prove valuable.

**Comment by serapath** [comment]
I'm currently writing my first mobile app (in the past - web apps only) and i'm using cordova and my custom stack which resembles facebok react (using virtual-dom, hyperscript and jss to do styles in javascript)

Nina said there are many projects who post all kinds of stuff around refugees (airbnb for refugees, free stuff for refugees, here it's jobs for refugees, maybe someone does events for refugees and others do again something else)
So there could be a listing which supports filters and all kinds of stuff. The project could be a single page app or frontend only thing (which means a mobile app too) and through an API all the items to show are fetched from different backends, namely those existing app projects

**Comment by Dahie** [comment]
I started with the API and created a pull-requests with some basics: https://github.com/RefugeesWork/RefugeesWork/pull/3
Adding more endpoints with more refined requirements should be easy from here. :)
